version: '3.8'

services:
  mongo1:
    container_name: vc-mongo1
    image: mongo:7.0.4
    volumes:
      - "mongo1_vc_data:/data/db"
      - "mongo1_vc_config:/data/configdb"
    networks:
      - mongors-vc-network
    ports:
      - 27021:27021
    links:
      - mongo2
      - mongo3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs_voicecord", "--port",  "27021"]
  
  mongo2:
    container_name: vc-mongo2
    image: mongo:7.0.4
    volumes:
      - "mongo2_vc_data:/data/db"
      - "mongo2_vc_config:/data/configdb"
    networks:
      - mongors-vc-network
    ports:
      - 27022:27022
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs_voicecord", "--port",  "27022" ]
  
  mongo3:
    container_name: vc-mongo3
    image: mongo:7.0.4
    volumes:
      - "mongo3_vc_data:/data/db"
      - "mongo3_vc_config:/data/configdb"
    networks:
      - mongors-vc-network
    ports:
      - 27023:27023
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs_voicecord", "--port",  "27023" ]

networks:
  mongors-vc-network:
    driver: bridge

volumes:
  mongo1_vc_data:
  mongo2_vc_data:
  mongo3_vc_data:
  mongo1_vc_config:
  mongo2_vc_config:
  mongo3_vc_config:
